name: open_note
description: Text and Todo Note App.
publish_to: none
version: 3.0.0 

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dynamic_color: ^1.6.2
  equatable: ^2.0.5
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  intl: ^0.18.0

  local_note_provider:
    path: package/local_note_provider
  note_backup_provider:
    path: package/note_backup_provider
  note_provider:
    path: package/note_provider
  note_repository:
    path: package/note_repository
  settings_list:
    path: package/settings_list
  settings_repository:
    path: package/settings_repository
  share_plus: ^7.1.0
  shared_preferences_storage:
    path: package/shared_preferences_storage
  
  storage_provider:
    path: package/storage_provider
    
  url_launcher: ^6.1.9

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.24.3
  very_good_analysis: ^5.1.0
  
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Roboto
      fonts:
        - asset: asset/font/Roboto-Regular.ttf
  assets:
    - asset/font/
    - asset/icon/

flutter_icons:
  android: true
  adaptive_icon_background: '#35A0CB'
  adaptive_icon_foreground: 'asset/icon/adaptive_icon_foreground.png'
  image_path: 'asset/icon/launcher_icon.png'

flutter_intl:
  enabled: true 
  class_name: S
  main_locale: en_US
  arb_dir: lib/l10n/arb 
  output_dir: lib/l10n/generated 