name: open_note
description: Text and Todo Note App.
publish_to: 'none'

version: 3.0.0 

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.1
  dynamic_color: ^1.6.2
  equatable: ^2.0.5
  file_picker: ^5.2.5
  flutter_bloc: ^8.1.2
  flutter_speed_dial: ^6.2.0
  intl: any
  replay_bloc: ^0.2.3
  share_plus: ^6.3.0
  url_launcher: ^6.1.9
  
# Settings Provider
  local_settings_provider:
    path: package/local_settings_provider
  settings_repository:
    path: package/settings_repository

# Note Provider
  local_note_provider:
    path: package/local_note_provider
  note_repository:
    path: package/note_repository
  note_backup_provider:
    path: package/note_backup_provider

# Settings View
  settings_view:
    path: package/settings_view
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  dart_code_metrics: ^5.6.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  test: any

flutter:
  uses-material-design: true
#  generate: true
  fonts:
    - family: Roboto
      fonts:
        - asset: asset/font/Roboto-Regular.ttf
  assets:
    - asset/font/
    - asset/icon/

flutter_icons:
  android: true
  adaptive_icon_background: '#35A0CB'
  adaptive_icon_foreground: 'asset/icon/adaptive_icon_foreground.png'
  image_path: 'asset/icon/launcher_icon.png'

flutter_intl:
  enabled: true 
  class_name: S
  main_locale: en_US
  arb_dir: lib/l10n/arb 
  output_dir: lib/l10n/generated 