name: note_backup_provider
description: A provider that handles note backups to and from file.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  file: ^6.0.0
  
  note_provider:
    path: ../note_provider

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
