name: note_backup_provider
description: A note backup implementation providing file I/O for notes.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: any
  path: ^1.8.2
  note_provider:
    path: ../note_provider