name: local_settings_provider
description: A Flutter implementation of the SettingsProvider that uses local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  settings_provider:
    path: ../settings_provider
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0