name: hive_storage
description: A Hive implementation of the StorageProvider interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  hive: ^2.2.3
  storage_provider:
    path: ../storage_provider
  synchronized: ^3.1.0
  
dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
