name: note_repository
description: A repository that handles note related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  path: ^1.8.2

  note_provider:
    path: ../note_provider
  note_backup_provider:
    path: ../note_backup_provider
